# CoMe ContextMemory config

Common:
  FileCacheExpire: 30
  MinImageQuality: 20
  CompressImageSizeAttempt: 5
  CompressImageSizeFactor: 0.7

LLM:
  ChatRequestTimeout: 300

llm_presets:
  CONTEXT_MEMORY:
    endpoint: https://api.deepseek.com/chat/completions
    token: ""
    model: deepseek-v4-flash
    api_type: "openai"
    max_context: 1000000
    auto_compress_gate: 0.7
    extra_parameter: {"thinking": {"type": "disabled"}}
    proxy_mode: ""
    price: {}

  KIMI2.6:
    endpoint: https://api.siliconflow.cn/v1/chat/completions
    token: sk-fetujatdhuuggekxfrxnyffjkmfhziizckifpursblmuobxk
    model: Pro/moonshotai/Kimi-K2.6
    api_type: "openai"
    max_context: 256000
    auto_compress_gate: 0.7
    extra_parameter: {}
    proxy_mode: ""
    price: {}

proxies:
  LOCAL_7890:
    http: "http://127.0.0.1:7890"
    https: "http://127.0.0.1:7890"

Logging:
  stdout_enabled: true
  write_error_file: true
  error_log_file: "logs/error.log"
